### PR TITLE
Add BOOST_NO_CXX17_IF_CONSTEXPR.

### PR DESCRIPTION
**Pull request by tzlaine**

### CODE REVIEW

**Comment by tzlaine** [comment]
Third time's the charm.  This passes all tests now.  Needed by Yap before it can be integrated as a Boost module.

**Comment by Lastique** [comment]
It might be useful to verify in the test the `if constexpr` statement actually discards one of the branches. For example, add a failing static assert in a dependent context.

**Comment by jzmaddock** [comment]
Other than Lastique's useful suggestion, this all looks good to me.  However, I won't merge until after the release.

**Comment by tzlaine** [comment]
Good idea.  I've added a static_assert to one of the false paths.

**Pull request merged**
