### PR TITLE
Add BOOST_NO_CXX17_ITERATOR_TRAITS macro.

### PR DESCRIPTION
**Pull request by Lastique**
The macro indicates that the standard library does not implement SFINAE-friendly
`std::iterator_traits` (LWG issue 2408 http://cplusplus.github.io/LWG/lwg-defects.html#2408, [iterator.traits]/2).

### CODE REVIEW

**Comment by jzmaddock** [comment]
My only query - is it really correct that libc++ doesn't support this - they're normally right at the forefront of these new features?

**Comment by Lastique** [comment]
The feature is not implemented according to https://libcxx.llvm.org/cxx1z_status.html (search for 2408). Travis tests also passed, suggesting that this is truly the case.

**Comment by jzmaddock** [comment]
On 21/07/2017 18:52, Andrey Semashev wrote:
>
> The feature is not implemented according to 
> https://libcxx.llvm.org/cxx1z_status.html (search for 2408). Travis 
> tests also passed, suggesting that this is truly the case.
>

If I'm reading that correctly, it's implemented in latest SVN but not 
released as such?

BTW the Travis tests don't currently catch macros that are unnecessarily 
defined, but whatever, will merge shortly.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Comment by Lastique** [comment]
> If I'm reading that correctly, it's implemented in latest SVN but not released as such?

My understanding of the second table is that it lists issues that were resolved by the Committee but not yet implemented in libc++. Maybe I got confused. In any case, libc++ 3.9.1 that I have locally doesn't implement it and we generally don't support unreleased versions of compilers.

I'll watch the test matrix if test failures appear. Thanks.

**Comment by Lastique** [comment]
Could you merge this PR and https://github.com/boostorg/config/pull/162 to master, please?

**Comment by jzmaddock** [comment]
On 24/08/2017 11:15, Andrey Semashev wrote:
>
> Could you merge this PR and #162 
> <https://github.com/boostorg/config/pull/162> to master, please?
>

See https://github.com/boostorg/config/pull/183, just waiting for CI to 
cycle.

---
This email has been checked for viruses by AVG.
http://www.avg.com

**Pull request merged**
