### PR TITLE
Haiku: remove invalid feature definitions

### PR DESCRIPTION
**Pull request by jessicah**
- Fixes the functional/hash library
- Fixes problems with the thread library

### CODE REVIEW

**Comment by jzmaddock** [comment]
I'll merge this from develop when master is open again.

**Comment by jessicah** [comment]
If there will be an rc4 to go out, may this and the other request be considered for inclusion?

**Comment by jzmaddock** [comment]
> If there will be an rc4 to go out, may this and the other request be 
> considered for inclusion?
>
Sorry, but as mentioned on the mailing list it's too late for anything 
except complete show-stoppers now.

**Comment by jessicah** [comment]
As I mentioned on the list, without these, it pretty much is a showstopper for the Haiku platform, whose support I only managed to finally get merged in the beta.

**Comment by jzmaddock** [comment]
> As I mentioned on the list, without these, it pretty much is a 
> showstopper for the Haiku platform, whose support I only managed to 
> finally get merged in the beta.
>
I understand, but this is support for a new platform, not a regression.  
If you want to ask the release managers on the mailing list for 
permission to merge by all means do so, but I can be pretty sure what 
their answer will be.

**Comment by jessicah** [comment]
Can this be merged now?

**Comment by jzmaddock** [comment]
Done.

**Pull request closed without merging**
