### PR TITLE
Add code to set for BOOST_NO_CXX98_RANDOM_SHUFFLE and BOOST_NO_CXX98_…

### PR DESCRIPTION
**Pull request by mclow**
…BINDERS correctly

This will fix compilation failures when building Boost.Test with clang v.50 and -std=c++1z or 2a

### CODE REVIEW

**Comment by mclow** [comment]
Sorry for the copy/paste error. Updated.

**Comment by jzmaddock** [comment]
Thanks chaps.

**Comment by mclow** [comment]
John - can you merge this change to master, please? I'd like to get this in the 1.65.0 release.

**Comment by jzmaddock** [comment]
On 09/08/2017 16:48, Marshall Clow wrote:
>
> John - can you merge this change to master, please? I'd like to get 
> this in the 1.65.0 release.
>

Done.


---
This email has been checked for viruses by AVG.
http://www.avg.com

**Pull request merged**
