### PR TITLE
Added defect macro BOOST_NO_CXX11_HDR_EXCEPTION

### PR DESCRIPTION
**Pull request by dmenendez-gruposantander**
Attempt to solve issue #284

### CODE REVIEW

**Comment by dmenendez-gruposantander** [comment]
Only tested locally on VS2015 and VS2017, not sure how I can test on other compilers that actually need the macro defined.
Advice welcome.

**Comment by dmenendez-gruposantander** [comment]
The travis CI is failing because I need to update the config for gcc in C++03 mode.
I could give it a try but I'm not sure trial and error is the best way forward, specially without being able to test with gcc locally.

**Comment by dmenendez-gruposantander** [comment]
OK, now I think all the tests should pass, but there seems to be something broken somewhere else in the CI tests.

**Comment by jzmaddock** [comment]
>OK, now I think all the tests should pass, but there seems to be something broken somewhere else in the CI tests.

There is, I'm working on it.

**Comment by dmenendez-gruposantander** [comment]
> > OK, now I think all the tests should pass, but there seems to be something broken somewhere else in the CI tests.
> 
> There is, I'm working on it.

Now that the 1.71 release is out, how can I retry this PR?
Should I rebase everything on the latest devel?
Are the CI problems sorted out?

**Comment by jzmaddock** [comment]
I'll sort that shortly, can I have your real name please?  The copyright on the test case should carry your name not Beman's.

**Comment by jzmaddock** [comment]
Replaced by https://github.com/boostorg/config/pull/293

I still need a name though.

**Pull request closed without merging**
