### PR TITLE
fixes warning in clang-6

### PR DESCRIPTION
**Pull request by HDembinski**
Addresses #300

### CODE REVIEW

**Comment by jzmaddock** [comment]
Thanks for that.

Can you please report upstream to clang, as it seems unreasonable for `__has_cpp_attribute(nodiscard)` to report `true` when `-pedantic -Werror` will result in a compiler error!

**Comment by HDembinski** [comment]
I will try to report it upstream. Registering on the LLVM bug-tracker is surprisingly complicated, apparently they are having problems with spam.

**Comment by HDembinski** [comment]
Actually, maybe we misunderstood the usage of `__has_cpp_attribute`. Despite the name, it does not only return true and false, but the date when the feature was added to the C++ standard.
https://en.cppreference.com/w/cpp/feature_test

So we maybe we should test like this?

```
#if __has_cpp_attribute(nodiscard)  >= __cplusplus
#define BOOST_ATTRIBUTE_NODISCARD [[nodiscard]]
#else
#define BOOST_ATTRIBUTE_NODISCARD
#endif
```

**Comment by jzmaddock** [comment]
The problem is that msvc still defines __cplusplus to 199711 :(

**Comment by HDembinski** [comment]
Ah, ok. Then we should probably keep it as is. :)

**Comment by jzmaddock** [comment]
>Ah, ok. Then we should probably keep it as is. :)

That's the easy solution, but I suspect that technically you are correct and this may all come back to bite us whatever....

**Pull request merged**
