### PR TITLE
Update last known MSVC version to 19.11.25506 (VS2017.3).

### PR DESCRIPTION
**Pull request by gongminmin**
Update the version number to VS2017.3's.

### CODE REVIEW

**Comment by MarcelRaad** [comment]
According to https://blogs.msdn.microsoft.com/vcblog/2017/08/11/c17-features-and-stl-fixes-in-vs-2017-15-3, structured bindings are now supported, so `BOOST_NO_CXX17_STRUCTURED_BINDINGS` probably shouldn't be defined for `_MSC_VER` >= 1911?

**Comment by jzmaddock** [comment]
Merged, I'll deal with any new features and changed config macros later: unless someone would like to submit a PR of course :)

**Comment by KindDragon** [comment]
@MarcelRaad @jzmaddock Boost Config test `no_cxx17_structured_bindings` pass for VC2017U3

**Comment by MarcelRaad** [comment]
@KindDragon I've just tried this too today and created PR #179 :-)

**Comment by glenfe** [comment]
PR 179 looks good. Note that there's no rush to get it into 1.65 because the developer that I added BOOST_NO_CXX17_STRUCTURED_BINDINGS for has not yet even submitted his pull request that would make use of it. :)

**Comment by Croydon** [comment]
Sorry, for not having an overview here.

What is/will be the first stable Boost release, which includes this pull request?

**Comment by jzmaddock** [comment]
It's in 1.65.1

**Pull request merged**
